apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: prometheus-cpu-template
spec:
  args:
  - name: service-name
  - name: preview-hash
  - name: baseline-hash
  metrics:
  - name: prometheus-cpu-template
    interval: 3m
    initialDelay: 120s
    count: 1
    # NOTE: prometheus queries return results in the form of a vector.
    # So it is common to access the index 0 of the returned array to obtain the value
    successCondition: result[0] >= 0.75
    failureLimit: 1
    provider:
      prometheus:
        address: http://prom-prometheus-server.prom:80
        query: |
          avg(rate(container_cpu_usage_seconds_total{namespace="$booinfo-sns", pod=~".*.*{{args.preview-hash}}.*"}[1m])) /
          avg(rate(container_cpu_usage_seconds_total{namespace="$booinfo-sns", pod=~".*.*{{args.baseline-hash}}.*"}[1m]))
