apiVersion: v1
kind: ConfigMap
metadata:
  name: productpage
data:
  providerConfig: |
    application: bookinfo-411-sns
    user: admin
    gateUrl: 'https://helm411-isd.isd-dev.opsmx.net/'
    lifetimeMinutes: 3
    gitops: true
    passScore: 90
    serviceList: 
    - metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
      baselineMetricScope: "bookinfo-411-sns,.*{{env.STABLE_POD_HASH}}.*,productpage"
      canaryMetricScope: "bookinfo-411-sns,.*{{env.LATEST_POD_HASH}}.*,productpage"
      metricTemplateName: "metrixtemplates"
      serviceName: productpage
